### ISSUE TITLE
 为什么应用程序显示不是64位的程序 根本打不开啊  ClashR for Windows 主应用程序打不开

### ISSUE THREAD

**Issue by a8682192** [BoyceLig/ClashR_for_Windows#12]
is:issue is:open  为什么应用程序显示不是64位的程序 根本打不开啊  ClashR for Windows 主应用程序打不开 用CMD 命令显示不是64位程序 而且单独能把哪个文件下下来  当然也打不开V shoujimimi8429 想问一下

**Comment by BoyceLig** [comment]
用新版clash吧，新版的clash已经支持了SSR了，这可能是你的系统问题，或者你系统是32位的。
