### ISSUE TITLE
还会继续更新新版本吗

### ISSUE THREAD

**Issue by GalensGan** [BoyceLig/ClashR_for_Windows#4]
请问下作者，我看 clash 的核心已经更新到了 1.0，这边后续会相应更新吗？

**Comment by BoyceLig** [comment]
没有合适的内核

**Comment by BoBppy** [comment]
@BoyceLig https://github.com/BROBIRD/clash
这个如何呢

**Comment by BoyceLig** [comment]
不行，她只能用于他自己开发的那个版本
