### ISSUE TITLE
软件会提示clash的更新

### ISSUE THREAD

**Issue by dukh1216** [BoyceLig/ClashR_for_Windows#5]
作者应该是没有修改更新的目的地址，打开软件后clashr for windows的标题会有红字更新提示，点击会跳转网页下载最新版的clash，希望作者取消这个更新提示或者把目的地址指向当前项目

**Comment by BoyceLig** [comment]
我不太会呀，我只是汉化加替换内核，里面的所有参数没变过，也是我之前的初衷。

**Comment by dukh1216** [comment]
> 我不太会呀，我只是汉化加替换内核，里面的所有参数没变过，也是我之前的初衷。

好的吧 辛苦啦

**Comment by dukh1216** [comment]
> 我不太会呀，我只是汉化加替换内核，里面的所有参数没变过，也是我之前的初衷。

对了 汉化版clashR提示更新的logo文字是“新建”，作者可不可以看一下是不是错了？

**Comment by BoyceLig** [comment]
> > 我不太会呀，我只是汉化加替换内核，里面的所有参数没变过，也是我之前的初衷。
> 
> 对了 汉化版clashR提示更新的logo文字是“新建”，作者可不可以看一下是不是错了？

不影响使用暂时就不改了
