### ISSUE TITLE
请教macOS版ClashR问题

### ISSUE THREAD

**Issue by JustCrazyer** [BoyceLig/ClashR_for_Windows#7]
您好，我是macOS系统，使用Fndroid的clash for Windows.dmg版本，关注到您有发布clashR for Windows，但是没有macOS版本，如果使用clashR，我需要替换哪几个文件？可以告知吗？
谢谢！

**Comment by BoyceLig** [comment]
我没有Mac系统，她的Mac版本我没试过。不好意思没帮带您

**Comment by JustCrazyer** [comment]
> 我没有Mac系统，她的Mac版本我没试过。不好意思没帮带您

谢谢回复
